name: CI Python
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci-python:
    strategy:
      matrix:
        operatingSystem: [ubuntu-latest, macos-latest, windows-latest]
        pythonVersion: [3.7, 3.8]
        node-version: [16]
    runs-on: ${{ matrix.operatingSystem }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }
      - name: Set up Python ${{ matrix.pythonVersion }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pythonVersion }}
      - name: Setup tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          python -m pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest
      - name: Run pylint
        run: |
          python -m pylint genbit
